---
- name: Configure sudo
  tags: sudo
  become: true
  block:
    - name: Add users to sudo group
      user:
        name: "{{ item }}"
        groups:
          - sudo
        append: true
      with_items: "{{ sudo_users }}"

    - name: Allow users in the sudo group to use sudo without providing their password
      community.general.sudoers:
        name: sudo
        group: sudo
        commands: ALL
        nopassword: true
